baseURL = '/'
languageCode = 'en-us'
title = 'snabilah'
theme = "theme"

[menu]
[[menu.main]]
  identifier = 'home'
  name = 'home'
  url = '/'
  weight = 1
[[menu.main]]
  identifier = 'posts'
  name = 'posts'
  url = '/posts'
  weight = 2
[[menu.main]]
  identifier = 'resume'
  name = 'cv'
  url = '/resume'
  weight = 3

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
